### PR TITLE
Allow lib to be installed by Angular 5

### PR DESCRIPTION
**Pull request by ssuperczynski**

### CODE REVIEW

**Comment by noemi-salaun** [comment]
Hello @ssuperczynski, thanks for the PR.

But I don't think it will be enough to be compatible with Angular 5. The latest AOT version uses a new version of the metadata generated during the build.

When I tried it last week, I couldn't make it work with v5 😞

**Comment by ssuperczynski** [comment]
Hey @noemi-salaun, I've added ng-packagr for AOT support. You can check `npm run bundle` works fine now. Just test need to be fixed. If you could point me how to fix them:

```
Chrome 62.0.3202 (Mac OS X 10.12.6): Executed 0 of 0 ERROR (0.003 secs / 0 secs)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nsalaun/ng-logger@3.0.0 karma:once: `npm run tsc && karma start karma.conf.js --single-run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @nsalaun/ng-logger@3.0.0 karma:once script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by noemi-salaun** [comment]
Hello @ssuperczynski, I changed all the build process.

It is now based on https://github.com/robisim74/angular-library-starter, recently updated for Angular 5.

Thank you for your effort :smiley:

You can update your dependencies now to use `@nsalaun/ng-logger` 5.0.0.

**Comment by ssuperczynski** [comment]
Thanks mate 🚀

**Pull request closed without merging**
