### PR TITLE
fix: Replace deprecated OpaqueToken with InjectionToken

### PR DESCRIPTION
**Pull request by chunghha**
fixes https://github.com/noemi-salaun/ng-logger/issues/11

### CODE REVIEW

**Comment by chunghha** [comment]
@noemi-salaun do you want to have Level to InjectionToken like this?
`export const LOGGER_LEVEL = new InjectionToken<Level>('LoggerLevel');`

Even with that, assume the case of passing invalid log level, having type won't get any help, there will be just no logging, same as current.
 `NgLoggerModule.forRoot('Hello'),`

which I can code with
 ```
constructor( @Inject(LOGGER_LEVEL) level: Level) {

        if (level in Level) {
            this._level = level;
        } else {
            console.log(`No logging by invalid log level ${level}`);
        }
```
with/without giving Level to the InjectionToken.

I know the difference between OpaqueToken and InjectionToken as you mentioned. But, I'd like to ask what's your thoughts on requesting changes for this case.

**Comment by noemi-salaun** [comment]
I don't think Typescript allow an invalid Level value if we type hint with InjectionToken<Level>.

If you talk about runtime, it may be overkill to assert every parameter type. We lose interest in using typescript in that case.

For this PR and the related issue #11, we should keep it simple and replace the OpaqueToken with InjectionToken<Level> only.

**Comment by chunghha** [comment]
I didn't want to introduce another type to check log level on the InjectionToken either. So are you going to accept this PR as-is?

Besides, I am sure you already know why I want to bring in this change at this time. Do you have a plan to support Angular 5 pretty soon?

**Comment by noemi-salaun** [comment]
Please just add the type hint in the InjectionToken

`export const LOGGER_LEVEL = new InjectionToken<Level>('LoggerLevel');`

I will accept this PR after it

I will add Angular 5 support before publishing the new release, as soon as possible ;)

**Comment by chunghha** [comment]
Good to hear, ASAP :)

Squashed the commit so please review.

**Comment by noemi-salaun** [comment]
@chunghha thanks for your help :)

**Comment by noemi-salaun** [comment]
@chunghha I publish the new release, without Angular 5 support.

With the next Angular, there are changes in the AOT metadata and I don't manage to make it work. The bundling works, but when using it in another project, I get `Uncaught Error: Can't resolve all parameters for Logger: (?).`

I'll wait for the Angular 5 release to work further into it. Maybe with some Angular library starter

**Pull request merged**
