### PR TITLE
doc: add example for environment log level

### PR DESCRIPTION
**Pull request by blackholegalaxy**
ping @noemi-salaun 

# PR Content
Add example to change log level depending on environment, as it seems to be a recurrent question on StackOverflow.
Fix copyright symbol.

# Discussion
Since your licence is MIT, did you think about only putting "MIT" in the licence part of README? It already contains your name copyright.

### CODE REVIEW

**Comment by noemi-salaun** [comment]
ping @blackholegalaxy 

Hello, thx for the PR.

I agree with you, it can be a good idea to show how to set the log level depending on environment :thumbsup:

Did you intentionnaly add the "+" signs at the begining of each line of your code exemple ? 

For the license, I do not have any knowledges about it, I just copied the way of doing of others known projects. What is the problem with writing my name in the license section ? :confused:

**Comment by blackholegalaxy** [comment]
Not a problem, just another way of presenting the license section. 

+ sign is to highlight what exactly is added to obtain the desired result. You can remove it if you want.

Un petit bonjour du Québec au passage ;)

**Comment by noemi-salaun** [comment]
Tu as su que j'étais français juste en voyant mon anglais dégueux ? :smile:

Bref... Je ne suis pas fan du "+" en début de ligne, je vais les retirer après avoir merge :wink:

**Comment by blackholegalaxy** [comment]
Non c'est marqué dans ton profil Github :) Si tu enlève les + au lieu de "diff" après les triple backtick.

**Pull request merged**
